---
tree:
  cache: true
remove: 
  method: 'mv'
  path: './trash'
archive:
  path: './tmp'
upload:
  path: './upload'
app_root: '/'
session_secret: 'iQEGLKa@@asfkj12irj91r0#$aijfksju1' #Change this
port: 4859
https:
  enabled: false
dev: true
